# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - run: ./scripts/system_install
      - run: make
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  lint:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - run: ./tests/lint/test

  client_launch_usage:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ./tests/client_launch/usage/test

  front_end:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ./tests/front_end/test

  back_end:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ./tests/back_end/test

  rsa:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ./tests/rsa/test

  block_chain:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ./tests/block_chain/test

workflows:
  linux:
    jobs:
      - build
      - lint:
          requires:
            - build
      - front_end:
          requires:
            - build
      - back_end:
          requires:
            - build
      - client_launch_usage:
          requires:
            - build
      - block_chain:
          requires:
            - build
      - rsa:
          requires:
            - build
