# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go build ./...
      - run: go test ./...
workflows:
  linux:
    jobs:
      - build_test
