#!/bin/bash
set -euo pipefail

REPO_ROOT=$(realpath $(dirname $BASH_SOURCE)/../../../)
TEST_DIR=$(realpath `dirname $BASH_SOURCE`)

ACTUAL_RES=$(mktemp)

set +e
$REPO_ROOT/build/client_launch/client_launch > $ACTUAL_RES 2>&1
set -e

if diff "$ACTUAL_RES" "$TEST_DIR/result" -q ; then
  echo "$TEST_DIR SUCCESS"
  rm -rf $ACTUAL_RES
  exit 0
else
  diff "$ACTUAL_RES" "$TEST_DIR/result" -y
  rm -rf $ACTUAL_RES
  exit 1
fi
