#!/bin/bash
set -euo pipefail
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt update
sudo apt install -y \
  make \
  g++ \
  python3.8 \
  libpython3.8-dev \
  python3.8-dev \
  libconfig++-dev \
  libssl-dev \
  clang-format
python3.8-config --ldflags
