#!/bin/bash
set -euo pipefail
if [ "$(uname)" == "Darwin" ]; then
  # this is a machintosh machine
  brew tap drolando/homebrew-deadsnakes
  brew update
  brew install -y
    make \
    g++ \
    python3.8 \
    libpython3.8-dev \
    python3.8-dev \
    libconfig++-dev \
    libssl-dev \
    clang-format
else
  # this is a debian linux machine
  sudo add-apt-repository -y ppa:deadsnakes/ppa
  sudo apt update
  sudo apt install -y \
    make \
    g++ \
    python3.8 \
    libpython3.8-dev \
    python3.8-dev \
    libconfig++-dev \
    libssl-dev \
    clang-format

  # lib p2p dependencies
  sudo pip3 install cmake --upgrade
fi
python3.8-config --ldflags
